
from api import API

# 1 - WSGI compliant
# def app(environ, start_response):
#     response_body = b"Hello, World!"
#     status = "200 OK"
#     start_response(status, headers=[])
#     return iter([response_body])

# 2 - WebOb compliant
app = API()

@app.route_create("/")
def home(request, response):
    response.text = f"Welcome to the <b>deramahmud</b> Python Framework, full of mistakes💥!"

@app.route_create("/hello/{name}")
def hello(request, response, name):
    response.text = f"Hello, {name}!"

# @app.route_create("/home")
# def home(request, response):
#     response.text = "Hello from the HOME page"
@app.route_create("/home")  # This overwrites the first handler! -> thats a problem
def home2(request, response):
    response.text = "Hello from the SECOND HOME page"


# Django-style class-based views 
@app.route_create("/books")
class BooksResource:
    def get(self, request, response):
        response.text = "List all books"
    
    def post(self, request, response):
        response.text = "Create a new book"

@app.route_create("/users/{id:d}")
class UserResource:
    def get(self, request, response, id):
        response.text = f"Get user {id}"
    
    def put(self, request, response, id):
        response.text = f"Update user {id}"
    
    def delete(self, request, response, id):
        response.text = f"Delete user {id}"

# New Django-style route
def sample_handler(req, resp):
    resp.text = "Django-style route example"
app.add_route("/sample", sample_handler)

def books_handler(req, resp):
    resp.text = "All books from Django-style route"

app.add_route("/django-books", books_handler)


# Initialize with template directory
app = API(templates_dir="templates")

# Use in handlers
@app.route("/template")
def template_handler(req, resp):
    resp.body = app.template("index.html", context={
        "name": "dearmahmud",
        "title": "Mahmud's Framework"
    }).encode() # if use resp.text = .encode() is not needed, but if use resp.body = .encode() is needed to convert string to bytes

# To run the server, and verify the routes, you can use the following curl commands:
"""
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$ curl http://localhost:8082/books
List all books(venv) 
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$ curl http://localhost:8082/users/123
Get user 123(venv) 
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$ curl -X POST http://localhost:8082/books
Create a new book(venv) 
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$ curl -X PUT http://localhost:8082/users/123
Update user 123(venv) 
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$ curl -X DELETE http://localhost:8082/users/123
Delete user 123(venv) 
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$ curl -X PATCH http://localhost:8082/books
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)(venv) 
dearm@Mahmud-LAPTOP MINGW64 /p/Projects/Python_3.0_Po/M_020-Build-Framework/My_Framework (main)
$


And the server logs show the following error:
  File "P:\Projects\Python_3.0_Po\M_020-Build-Framework\My_Framework\api.py", line 86, in handle_request
    raise AttributeError("Method not allowed", request.method)
AttributeError: ('Method not allowed', 'PATCH')
"""